apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: dsdsocket
      containers:
        - name: example
          image: localhost:5000/example:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
              readOnly: true
          env:
            - name: DD_AGENT_SOCKET_PATH
              value: /var/run/datadog/dsd.socket
